-completed react-events-and-state
btoomepuu/rc0622-code-solutions pull request #112
Opened 2022-09-01 19:12 UTC by btoomepuu

https://user-images.githubusercontent.com/59620542/187993945-d1881723-6616-4b01-890c-f2f39de5a190.mov

2022-09-01 19:39 UTC, scbowler requested changes
A few updates needed. Let me know if you have any questions.

2022-09-01 19:39 UTC, scbowler commented on react-events-and-state/src/index.jsx
> +    this.props.text = 'Thank you!';
`this.props` should be read only, we never directly set `this.props` from inside the component.

2022-09-01 19:39 UTC, scbowler commented on react-events-and-state/src/index.jsx
> +  }
Here you should use an `if` statement to set the correct text in the button based on the value in `this.state`, not `this.props`.
```JSX
if (this.state.isClicked) {
  return <button>Thank You!</button>;
} else {
  return <button onClick={this.handleClick}>Click Me!</button>;
}
```

2022-09-01 19:39 UTC, scbowler commented on react-events-and-state/src/index.jsx
> +const element = <CustomButton text="Click Me!" />;
No need to pass the `text` props here, for this exercise.

2022-09-02 17:05 UTC, TimelikeClosure approved these changes

2022-09-02 17:31 UTC, merged